### ISSUE TITLE
Multiple requests for extension?

### ISSUE THREAD

**Issue by vagrantsn** [plouc/mozaik-ext-github#17]
I need to gather information from two endpoints at the same time. Is there some way to set up multiple request to getApiRequest?

Thanks!

**Comment by plouc** [comment]
No, there isn't, but you can add a new operation on the client, not optimal but it works.

**Comment by vagnervst** [comment]
Great, thanks for the answer!

Also, one more thing: is it possible to create widgets that deal with events? I am creating a widget that uses a search input to filter the results (a list of repos). I tried a few things but couldn't get it to work. Do you have any ideas?

Thanks, Plouc!
