### ISSUE TITLE
Install fails without exact version (release needed without -beta flag)

### ISSUE THREAD

**Issue by juhamust** [plouc/mozaik-ext-github#2]
Seems that the behavior of NPM has changed: If the module that has no stable release (only ones with -beta flag in version name) available, exact version names are needed on installing:

``` shell
# Install release with stable release
npm i mozaik-ext-bamboo
OK

# Install module with only -beta releases
npm i mozaik-ext-aws 
npm ERR! Linux 4.0.5-1-ARCH
npm ERR! argv "node" "/usr/bin/npm" "i" "mozaik-ext-aws"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: mozaik-ext-aws@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.1-beta","0.0.2-beta","0.0.3-beta","0.0.4-beta","0.0.5-beta","0.0.6-beta","0.0.7-beta","0.0.8-beta","0.0.9-beta","0.0.10-beta","0.0.11-beta","0.0.12-beta"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that does not exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/juha/tmp/moz/npm-debug.log

# Install module with exact version
npm i mozaik-ext-aws@0.0.12-beta
OK
```

This issue currently applies with all the mozaik extensions released by you, @plouc. I'd propose to make "stable" releases from each, as it prevents also `mozaik-demo` to install out of the box.

**Comment by juhamust** [comment]
Apparently, this happens now in node 0.10.x too, with npm version  v2.11.3.

**Comment by plouc** [comment]
@juhamust I've updated some extensions and mozaik to 1.x, but not the aws one hasn't been updated, feel free to create an issue on the dedicated repo.
I've also changed the way extensions are loaded, you no more have to pre-compile jsx/es6, you can directly publish src and the top app (demo or extension) will handle transformation via babel automatically (won't be the case for <1.0.0 packages).
I also plan to make a table with all available extensions and their current version/build status to replace the simple list on the wiki.

**Comment by juhamust** [comment]
@plouc I believe the issue is having only `-beta` releases, it does not need to be >= 1.x per se.

**Comment by plouc** [comment]
yes, but I'd like to migrate to new structure, not remove the beta flag

**Comment by plouc** [comment]
It should be done soon

**Comment by juhamust** [comment]
Ok, good.

**Comment by plouc** [comment]
I close this issue as this extension is now available in non-beta version, feel free to create one on dedicated repos.

**Comment by plouc** [comment]
@juhamust here is the list of existing extensions with latest npm package version info http://plouc.github.io/mozaik/extensions/

**Comment by juhamust** [comment]
Good work :+1:
